# Generated by Django 3.0 on 2019-12-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20191226_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matirial',
            name='m_status',
            field=models.CharField(choices=[('存貨足夠：', '不用訂貨'), ('存貨不足', '記得訂貨')], default='存貨不足', max_length=50),
        ),
    ]
