# Generated by Django 3.0 on 2019-12-26 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20191226_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='todayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('sell_pd1', models.IntegerField(default=0)),
                ('sell_pd2', models.IntegerField(default=0)),
                ('sell_pd3', models.IntegerField(default=0)),
                ('sell_pd4', models.IntegerField(default=0)),
                ('sell_pd5', models.IntegerField(default=0)),
            ],
        ),
    ]
