# Generated by Django 3.0 on 2019-12-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_todayrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
