# Generated by Django 3.0 on 2019-12-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_delete_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todayRecord',
            new_name='DailyRecord',
        ),
    ]
