# Generated by Django 3.0 on 2019-12-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20191227_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=10)),
                ('p_price', models.IntegerField()),
                ('blacktea', models.IntegerField(default=0)),
                ('milk', models.IntegerField(default=0)),
                ('pearl', models.IntegerField(default=0)),
                ('taro', models.IntegerField(default=0)),
                ('honey', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='matirial',
            name='m_status',
            field=models.CharField(max_length=50),
        ),
    ]
