# Generated by Django 3.0 on 2019-12-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20191228_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matirial',
            name='m_status',
        ),
    ]
