# Generated by Django 3.0 on 2019-12-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_remove_matirial_m_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matirial',
            name='m_safe_inventory',
            field=models.IntegerField(),
        ),
    ]
