# Generated by Django 3.0 on 2019-12-31 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_auto_20191229_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='addMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
                ('add_blacktea', models.IntegerField(default=0)),
                ('add_milk', models.IntegerField(default=0)),
                ('add_pearl', models.IntegerField(default=0)),
                ('add_taro', models.IntegerField(default=0)),
                ('add_honey', models.IntegerField(default=0)),
            ],
        ),
    ]
