# Generated by Django 3.0 on 2020-01-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20200111_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addmaterial',
            options={'verbose_name_plural': '新增產品每日進貨量'},
        ),
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'verbose_name_plural': '產品每日銷售量'},
        ),
        migrations.AlterModelOptions(
            name='matirial',
            options={'verbose_name_plural': '原料量'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '各飲品原料用量'},
        ),
    ]
