# Generated by Django 3.0 on 2019-12-26 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_name', models.CharField(max_length=11)),
                ('c_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('c_sex', models.IntegerField()),
                ('c_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_num', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('item_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('item_sales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurRecord',
            fields=[
                ('trade_num', models.IntegerField(primary_key=True, serialize=False)),
                ('buy_amount', models.IntegerField(default=0)),
                ('buy_total', models.IntegerField()),
                ('pur_time', models.DateTimeField(auto_now_add=True)),
                ('c_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Customer')),
                ('item_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Item')),
            ],
        ),
    ]
