# Generated by Django 3.0 on 2019-12-26 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purrecord',
            name='c_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.CUSTOMER'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='item_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ITEM'),
        ),
    ]
