# Generated by Django 3.0 on 2020-01-01 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20191226_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purrecord',
            name='c_ID',
        ),
        migrations.AddField(
            model_name='customer',
            name='c_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='purrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.Customer'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='pur_time',
            field=models.CharField(max_length=7),
        ),
    ]
