# Generated by Django 3.0 on 2020-01-16 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20200102_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '會員'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': '各品項銷量'},
        ),
        migrations.AlterModelOptions(
            name='purrecord',
            options={'verbose_name_plural': '購買記錄'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='會員卡號'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='會員生日'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_name',
            field=models.CharField(max_length=11, verbose_name='會員姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_point',
            field=models.IntegerField(default=0, verbose_name='累計點數'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_sex',
            field=models.IntegerField(verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=20, verbose_name='品項名稱'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_num',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='品項編號'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='品項價格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_sales',
            field=models.IntegerField(default=0, verbose_name='銷量（杯）'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='buy_amount',
            field=models.IntegerField(default=0, verbose_name='購買數量'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='buy_total',
            field=models.IntegerField(verbose_name='購買總金額'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Customer', verbose_name='會員卡號'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='item_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Item', verbose_name='購買品項'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='pur_time',
            field=models.CharField(max_length=7, verbose_name='購買時間'),
        ),
        migrations.AlterField(
            model_name='purrecord',
            name='trade_num',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='交易記錄編號'),
        ),
    ]
